server:
  port: ${BACKEND_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:tutoruber-backend}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:true}
        dialect: ${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

app:
 cors:
  #  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://127.0.0.1:5500,http://localhost:5500}



